export { prepareTraceDir, readNdjson, getResourceBuffer, listTraces, getReportMetadata, buildReportTraceMaps, findTraces } from './parseTrace';
export type { TraceContext, ReportTestSummary, ReportMetadata, ReportTraceMaps, FoundTrace } from './parseTrace';

export {
  getTestSteps,
  getTopLevelFailures,
  getTestTitle,
  getNetworkTraffic,
  getNetworkRequest,
  getConsoleEntries,
  getTraceIssues,
  getAttachments,
  extractAttachment,
  extractScreenshots,
  getDomSnapshots,
  getTimeline,
  getSummary,
  getFailedTestSummaries,
  getReportFailurePatterns,
  summarizeReportFailurePatterns,
} from './extractors';

export type {
  ActionDiagnosticSummary,
  ConsoleEntry,
  StepAnnotation,
  TestStep,
  TraceError,
  TraceIssue,
  ReportFailurePatterns,
  RepeatedFailingRequestPattern,
  RepeatedIssuePattern,
  NetworkFilterOptions,
  NetworkEntry,
  RelatedActionRef,
  AttachmentEntry,
  SavedAttachment,
  Screenshot,
  ScreenshotMetadata,
  DomSnapshot,
  ActionDomSnapshots,
  DomSnapshotOptions,
  TimelineEntry,
  TraceSummary,
  GetSummaryOptions,
  GetFailedTestSummariesOptions,
  FailedTraceSelection,
} from './extractors';
